### ISSUE TITLE
Bell Icon (above No Notification text) disappear

### ISSUE THREAD

**Issue by Anifyuli** [realmazharhussain/gdm-tools#11] opened 2021-12-19 12:35 UTC
Hello, Bro Hussain.

I have a small problem with gdm-tools. Same as title of this issue, I see a bug or error in your theme because bell icon above no notification has dissappear in my favorite GNOME DE and tested all of theme too  (except Adwaita or default shell theme). I want you to fix that problem. This tool make my GDM fresh and matching with my theme

https://forum.manjaro.org/uploads/default/optimized/3X/2/3/23c481a029d802461c1017caf8729ebf62eb0bc9_2_690x387.jpeg

I wait your update on my Github timeline. I love this tool.

Thanks for your hardwork and favors.

CMIIW, my English is bad

**Comment by realmazharhussain** [comment] 2021-12-20 06:01
This is how your theme wants to show the notification area. It does not want the bell icon there. The theme itself needs to be modified to show that bell icon. If you know what to change in Theme's CSS to make that happen, you can modify `/etc/gdm-tools/custom.css` and CSS in `/etc/gdm-tools/custom.css` will be appended to the Theme's CSS (without modifying theme files in `/usr/share/themes`) before setting it.

I do not yet know what to change in Theme's CSS to make that happen.

If I do some day, I will comment it here.

**Comment by Anifyuli** [comment] 2021-12-21 12:48
So, your mean if I can editing `/etc/gdm-tools/custom.css` and `/etc/gdm-tools/custom.css` can resolve that problem, Bro?

**Comment by realmazharhussain** [comment] 2021-12-23 07:23
@Anifyuli, That's what I said. I don't know what to change. If I ever know, I will tell you.

AND

The problem is not with `gdm-tools`. It is with your theme.

**Comment by Anifyuli** [comment] 2021-12-23 08:44
Ok, thanks, Bro. If you see a theme what that theme haven't this problem, you can say it to me 😁

**Comment by realmazharhussain** [comment] 2021-12-23 09:23
OK

**Comment by realmazharhussain** [comment] 2022-01-02 05:58
Your problem is not solved yet. Why did you close the issue?

**Comment by Anifyuli** [comment] 2022-01-02 07:19
Sorry, I feel confused, Bro. Ok I will wait you

**Comment by realmazharhussain** [comment] 2022-01-02 07:21
What theme are you using?

**Comment by Anifyuli** [comment] 2022-01-02 07:25
For now I use Qogir what have GDM theme support. I only find 3 themes with GDM support and I tried it

**Comment by realmazharhussain** [comment] 2022-01-02 07:42
Can you tell me what version of Gnome Shell you use?
You can find out the version of Gnome Shell by running command `gnome-shell --version` in terminal.

And also What version of Qogir theme are you using? If you don't know that, you can tell me where did you get the theme from?

**Comment by Anifyuli** [comment] 2022-01-02 07:53
I use GNOME Shell v41.2 . I use Qogir theme 2021-12-25 version. I get that theme from Vince Github repo. This repo link [https://github.com/vinceliuice/Qogir-theme](url) to check it. And, I install this theme with script from him

**Comment by realmazharhussain** [comment] 2022-01-02 08:03
Sorry!

I thought the problem was with your theme. It turns out this is a bug in `gdm-tools`.

I'm working on it.

**Comment by Anifyuli** [comment] 2022-01-02 08:15
Ok, Bro. I glad to wait your progress. Thanks to accept my issue

**Comment by realmazharhussain** [comment] 2022-01-02 11:20
I think I have fixed the issue.

Please! Update `gdm-tools` and Check if it works and Inform me.

**Comment by Anifyuli** [comment] 2022-01-02 13:33
Ok, Bro. I was update gdm-tools. Wait, I check it

**Comment by Anifyuli** [comment] 2022-01-02 13:38
![Screenshot from 2022-01-02 20-36-35](https://user-images.githubusercontent.com/73734843/147877571-7c5b9445-094d-463f-8328-36dded910b7f.png)
It work well, Bro. Thanks for your hard work

**Comment by realmazharhussain** [comment] 2022-01-02 19:11
You are welcome

**Closed** 2022-01-02 19:11 UTC
Labels: bug
